### ISSUE TITLE
Deprecated Compiler

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/HeadMaster#13]
Hello @aterlumen @CrasherCourse and the rest,

So, just so you know, the C18 compiler is being phased out in favor of a new compiler, XC8. We could either try to convert over to XC8 before we start major work (DMX processing) or just keep going on C18 since its familiar.

What do you think?

**Comment by taylortrimble** [comment]
**C18 -> XC8**

Pros:
- We aren't using a deprecated compiler
- XC8 is designed to be super-super portable, which may be advantageous later on for similar (servo) projects
- XC8 is not that different than C18, and it's similar to High-Tech C (the "other" compiler than C18 before XC8 came out)
- Overall, XC8 is more standardized and technologically advanced (compile stages) than C18
- Better Microchip framework availability moving forward

Cons:
- We don't already know it
- We do have _some_ code to port
- Harder to get support from EE students in a pinch

I think this could be a good experience and marketable new shiny skill, and I kind of want to do it. However, there's danger involved so what do you guys think?

**Comment by kevana** [comment]
I'd be up for it.

**Comment by CrasherCourse** [comment]
I'm fine with that.  It'll be fun to mess with a new compiler.

**Comment by taylortrimble** [comment]
All right, sweet! I read through the [XC8 compiler documentation](http://www.microchip.com/mplabxc8guide) somewhat, really I found that chapter 2 was the most helpful. It basically describes what is different about using XC8 than past compilers.

Paper coming up soon, but after that I'll come up with a XC8/CCI compliant template.
