### ISSUE TITLE
Remove testing code from master

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/HeadMaster#16]
We're about to merge in some code (#14 and #15) and we'll want to be sure that it doesn't leave any test code in master. If it does, we'll remove it.

**Comment by taylortrimble** [comment]
@CrasherCourse I've assigned this issue to you; when the code goes in can you double check this? Messy merges might mean this is hard to head off before we merge the Pull Requests this round. :smiley:

**Comment by CrasherCourse** [comment]
Got it!

**Comment by taylortrimble** [comment]
Thanks!

**Comment by taylortrimble** [comment]
I think this is done.
