### ISSUE TITLE
DIP switch and LED pins

### ISSUE THREAD

**Issue by mistressoftheelectron** [teslaworksumn/HeadMaster#17]
Would it be a problem if I change which pins the DIP switch and LEDs connect to?  Currently the DIP is on port A, and the LEDs on port B.  I'd like to swap them.

It makes the PCB layout simpler, and lets us take advantage of the internal pullup resistors on port B.  This means eliminating a bunch of extra resistors.  It should be pretty trivial to change the code.

**Comment by taylortrimble** [comment]
That makes complete sense; go for it!

**Comment by kevana** [comment]
No objections from me.

**Comment by mistressoftheelectron** [comment]
Scratch that, I'm keeping the original plan.  Port B may have internal pullups, but it's also the only one which can directly supply the current to the LEDs.  The PCB is pretty much done now, and it's only about five cents worth of resistors.

**Comment by taylortrimble** [comment]
Can't port A _sink_ that much current for an LED?

**Comment by mistressoftheelectron** [comment]
Nope.  Port A can only source/sink a measly 4 mA per pin.  Port B can source/sink 25 mA per pin.  Crazy to not have internal pullups on every port, but apparently someone at microchip thought it was a good idea.

**Comment by taylortrimble** [comment]
MICROCHIP WHY!!?? Okay.
