### ISSUE TITLE
Individual Head controller I2C issues

### ISSUE THREAD

**Issue by kevana** [teslaworksumn/HeadMaster#2]
Will we run into any issues trying to use I2C for both sending data from the headmaster chip to the slaves, and from the slaves to the individual PWM chips?

**Comment by taylortrimble** [comment]
@aterlumen Good question. I think that the slave boards in our case _only are_ PWM chips. I don't think they have any intermediary logic.

**Comment by CrasherCourse** [comment]
@tylrtrmbl @aterlumen That's correct the slaves are the PWM chips.  Technically we're using reprogrammed microchips, but in theory they should simply be PWM chips.

**Comment by taylortrimble** [comment]
@CrasherCourse Excellent! Thank you. Also, feel free to "comment and close" in the future if there's a finality to your answer.
