### ISSUE TITLE
Oversized DMX receive buffer

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/HeadMaster#29]
Our DMX receive buffer is 512 (`DMX_BUFFER_SIZE`) bytes right now, but it could be shrunk to the number of heads' channels we are servicing. We can simply read into a dummy variable if it's a channel we don't want to keep and read into our (smaller) buffer if it's a value we do want to keep.

It adds a condition, but we could even stop reading after we fill up our smaller heads buffer. This could solve our #28 as well.

**Comment by kevana** [comment]
Referenced in #33.

**Comment by taylortrimble** [comment]
I think this is covered in #38. I'm going to close this issue due to that.
