### ISSUE TITLE
Incorrect PRAGMA code

### ISSUE THREAD

**Issue by kevana** [teslaworksumn/HeadMaster#3]
Will need to update everything for the PIC18F14K50

**Comment by CrasherCourse** [comment]
Turns out we're using a different chip than the PIC18F14K50.
But, we still need to update the PRAGMAs.

**Comment by taylortrimble** [comment]
Found out where the config directives are documented. You have to have the XC8 compiler installed, and the documentation is automatically installed alongside the compiler.

#### Access PIC18F2620 config bits for v1.10 (win: v1.11) of the XC8 compiler

Mac users:

```
open /Applications/microchip/xc8/v1.10/docs/chips/18f2620.html
```

PC users:

```
start 'C:\Program Files (x86)\Microchip\xc8\v1.11\docs\chips\18f2685.html'
```

or something like that. You get the idea.

Don't forget to swap out version numbers for future versions of the compiler.

#### Old C18 config bits

You can find the bits we used for the **PIC18F24J10** (not PIC18F2620) [here](http://ww1.microchip.com/downloads/en/DeviceDoc/MPLAB_C18_Config_Settings_51537c.pdf). Happy scrolling! We used these bits in our original (basis) project at b2b45d575c7d15679da3521d972d74f0933286ff.

We can use this to help us pick the correct config bits, although we may need to set a few more as well.

**Comment by CrasherCourse** [comment]
In masterChipSendSignal.c were the pragma config commented out to prevent compile errors?

**Comment by taylortrimble** [comment]
Yep!

**Comment by taylortrimble** [comment]
@CrasherCourse I saw you've got some progress done on this, are you ready to open a pull request yet?

**Comment by CrasherCourse** [comment]
@tylrtrmbl Now I am.

**Comment by taylortrimble** [comment]
Has a pull request open
