### ISSUE TITLE
CCP2MX config setting does not exist

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/HeadMaster#34]
When I try to build the project, I get the following error:

```
masterChipSendSignal.c:44: error: unknown configuration setting/register (CCP2MX = PORTC) used
```

Inspection of the documentation at `C:\Program Files (x86)\Microchip\xc8\v1.11\docs\chips\18f2685.html` shows that CCP2MX does not exist for the PIC18F2685.

I think we should remove it!

**Comment by kevana** [comment]
Ditto on my box, thought it was just me configuring mplab wrong.

**Comment by CrasherCourse** [comment]
Whoops!  That's because it belongs to PIC18F2620.
(-_- ) How many times do I have to get the PIC model wrong.

**Comment by taylortrimble** [comment]
Haha! Well, worse things have happened. Can you make sure the other settings are correct as well and we're not missing any? They should be more or less the same though.

**Comment by CrasherCourse** [comment]
The main addition is the boot block size selection bits (BBSIZ).
Seems important will check in a bit.

**Comment by taylortrimble** [comment]
@CrasherCourse Thanks! Did you find out more about this?

**Comment by CrasherCourse** [comment]
The boot block is used for boot loader routines to write to its own program memory.
The boot block can be set to either 1K, 2K, or 4K words (values: 1024, 2048, 4096 respectively.)
Since we aren't messing with boot loaders right now I would recommend setting the value to 1024.

**Comment by CrasherCourse** [comment]
Other things to add are protection bits CPX, WRTX, and EBTRX for blocks 4 and 5.

**Comment by taylortrimble** [comment]
Let's do it!

**Comment by CrasherCourse** [comment]
Should I do a pull request for those changes?
Or should I let them piggy back on another pull request?

**Comment by taylortrimble** [comment]
Naw, open a new pull request

**Comment by CrasherCourse** [comment]
Closing since I put up the pull request for this issue.
