### ISSUE TITLE
Setup code!

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/HeadMaster#44]
We need to initialize our hardware peripherals with the correct settings for our newly decided clock speed!

Anyone want to finish this before break is over?
@aterlumen @mplewis @CrasherCourse I'm looking at you guys. :eyes:

**Comment by taylortrimble** [comment]
This may or may not be our last issue before we have a "This **SHOULD** work" prototype (that won't work).

**Comment by mplewis** [comment]
I can take a look at this. I'll open up a wiki page for my tentative settings and discussion.

**Comment by taylortrimble** [comment]
Actually, use this issue! You can discuss here, and add a pull request once you have code. It doesn't even have to be right when you open the pull request, it's just a place where we can discuss the actual implementation.

**Comment by mplewis** [comment]
Sounds good to me. We should start getting a list of exactly what peripherals we need to reconfigure. USART is one.

**Comment by taylortrimble** [comment]
I think we have:
- USART for DMX (baud rate matches DMX)
- I2C to slave pwm generators in each head (not sure bout baud rate here)

**Comment by taylortrimble** [comment]
Plus the configuring the clock of the whole device properly for 40MHz `Fosc`

**Comment by mplewis** [comment]
Are we running in I2C fast mode or just standard I2C mode?

**Comment by taylortrimble** [comment]
I was about to ask you the same thing. I'm not sure looking at the code and documentation for our [slave](https://github.com/teslaworksumn/headslave). Might have to reverse engineer it from the chip's documentation and how it's set up in the current code.

**Comment by taylortrimble** [comment]
I know that DMX baud rate is 250k, so I think our USART has to be configured with that too

**Comment by taylortrimble** [comment]
D'oh. I2C has master-determined and provided clock line. So we just need to find out if our slave can take a full "standard mode" I2C signal using the super-slow 4MHz internal clock. I get the impression it was only tested using a LEGO Mindstorms brick, which only has a 9600 bits/s baud rate.

**Comment by mplewis** [comment]
From Wikipedia:

> Common I²C bus speeds are the 100 kbit/s standard mode and the 10 kbit/s low-speed mode, but arbitrarily low clock frequencies are also allowed.

That means we should be able to make it work.

**Comment by taylortrimble** [comment]
Okay, sweet. I think that low-speed has enough throughput for us, so let's target that!

**Comment by mplewis** [comment]
We're using a 10 MHz crystal. Using HSPLL mode --> 40 MHz Fosc.

`CONFIG1H: 00000110`
- no switchover or failsafe monitor
- HSPLL mode (Fosc = 4x primary oscillator))
- Datasheet pg. 344

`OSCCON: 01000000`
- use primary oscillator (10 MHz crystal)
- Datasheet pg. 30

[PIC18F2685 datasheet (PDF)](http://ww1.microchip.com/downloads/en/devicedoc/39761b.pdf)

**Comment by mplewis** [comment]
Datasheet pg. 231 has baud rate formulas.

DMX baud rate = 250 KHz
Fosc = 40 MHz
Baud rate = Fosc / (x (n + 1))
where x is either 64, 16, or 4, dependent on BRG/EUSART mode.

250 KHz = 40 MHz / (x (n + 1))
x (n + 1) = 160

Let x = 4 (that means we can use **3 modes**: 16-bit async, 8 bit sync, 16 bit sync)
Thus, n + 1 = 40, so **n = 39**

Let x = 16 (that means we can use **2 modes**: 8-bit async, 16-bit async)
Thus, n + 1 = 10, so **n = 9**

I'm guessing we want 8-bit asynchronous mode. Can you confirm, Taylor?

The only config supporting 8-bit asynchronous is:
`SYNC: 0, BRG16: 0, BRGH: 1`

So:
`TXSTA.SYNC: 0`
`BAUDCON.BRG16: 0`
`TXSTA.BRGH: 1`

**Comment by mplewis** [comment]
Details for setting up an EUSART async transmission are on datasheet pg. 236.

Details for setting up an EUSART async reception are on datasheet pg. 238.

**Comment by taylortrimble** [comment]
> We're using a 10 MHz crystal. Using HSPLL mode --> 40 MHz Fosc.
> `CONFIG1H: 00000110`

Usually for PIC microcontrollers, we don't set the registers directly for controller-wide settings such as clock speed. We usually instead use `#pragma config` directives. [This comment](https://github.com/teslaworksumn/HeadMaster/issues/3#issuecomment-10042628) describes how to get them for a different PIC, but it's more or less the same! :smiley: You do need MPLAB X and the xc8 compiler, however.

You can see what the current pragma directives are in our source already!

**Comment by taylortrimble** [comment]
> I'm guessing we want 8-bit asynchronous mode. Can you confirm, Taylor?

That is correct!

**Comment by taylortrimble** [comment]
Thank you @mplewis! Keep it up!

**Comment by kevana** [comment]
Good stuff.

**Comment by mplewis** [comment]
I've set up a branch: setup_code. I intend to have this done by tonight once I understand pragmas, which @tylrtrmbl tells me is easy.

**Comment by taylortrimble** [comment]
Feel free to open a pull request on that before you are ready to merge it, and we'll watch it as you go, and discuss, etc. Thanks @mplewis!

**Comment by mplewis** [comment]
I'm waiting for the XC8 compiler to download and working from the [C18 Config Settings guide](http://ww1.microchip.com/downloads/en/DeviceDoc/MPLAB_C18_Config_Settings_51537c.pdf) using the PIC18F2680 section as a guide.

Based on what I've posted above previously:

> - no switchover or failsafe monitor
> - HSPLL mode (Fosc = 4x primary oscillator))

I'm adding this code to the pragmas:

```
OSC = HSPLL
FCMENB = OFF
IESOB = OFF
```

> The only config supporting 8-bit asynchronous is:
> `SYNC: 0, BRG16: 0, BRGH: 1`

I can't find that in the document linked. Do we set up USART with pragmas?

**Comment by mplewis** [comment]
For reference, I've put the 18F2685 XC8 compiler docs online [here](http://www.mplewis.com/archive/18f2685.html). Enjoy.

**Comment by taylortrimble** [comment]
@mplewis, Thanks! :gift_heart:

**Comment by mplewis** [comment]
I need someone to look at #46, the code I'm modifying for this issue. I have a [line note](https://github.com/teslaworksumn/HeadMaster/pull/46#discussion_r2720517) detailing my question re: baud rate for DMX.

Can someone verify what baud rate we're targeting?

**Comment by mplewis** [comment]
#46 has been merged and this issue should be closed now.
