### ISSUE TITLE
How to test the software?

### ISSUE THREAD

**Issue by CrasherCourse** [teslaworksumn/HeadMaster#48]
Another self-explanatory title.

I believe we should have a mock show that just runs through all the servo channels.

I think @tylrtrmbl has a signal reading device we could use to check the outputs of our master and the slave chips without using the servos.

Also, is the a way to simulate any part of our master code on a computer?

**Comment by taylortrimble** [comment]
This definitely is HeadMaster-specific. It depends on what you mean by test: there are a few kinds of tests we could do:
- **Unit tests:** Testing individual functions in our code with other code, such as the `mapDmxToServo` function
- **Fixture tests:** Where we hook up our device to a physical signal, and test that it behaves properly. This looks most like what you're recommending
- **Integration tests:** In our case, the same as fixture tests, but testing only a subset (just I2C, just DMX, etc)
- **Simulations:** Same as Fixture/Integration tests, but we could probably rig something up using simulated signals as well

This is a big issue! What spots do you guys all see that we could use these in?

Note: Microcontrollers rely a lot on fixture testing, and just good old-fashioned no-test debugging traditionally. There won't be any nice, cute ways to do these, but it may be worth inventing some.

**Comment by kevana** [comment]
Testing the DMX library out of band would be ideal, but that my not be possible without a ton of extra effort. It compiles, but I wasn't able to do any real world testing on it to see how it behaves.

**Comment by taylortrimble** [comment]
I like the idea of a simulated test suite that @CrasherCourse mentioned. @CrasherCourse, can you actually be responsible for implementing that?

I think @aterlumen would be fully qualified to design a pretty nice smoke test too, using my I2C reading device and DMX output device.

**Comment by kevana** [comment]
Elaborate?

**Comment by taylortrimble** [comment]
I have a device that can read I2C and a device that can output DMX. You'd have to sit there and watch the test (which is why it's called a smoke test, btw) but you should be able to come up with a good test I think!

**Comment by taylortrimble** [comment]
Okay, so we have everything needed to test and the master board is done.

... guess it's time to go! Can we do this on Friday? The meeting portion at the front should be less than 10 minutes, so we can go to Keller and come back for pizza.

@aterlumen @mplewis @CrasherCourse

**Comment by mplewis** [comment]
:cool: :roller_coaster:

**Comment by CrasherCourse** [comment]
Can we do it?
...
Yes we can!
