### ISSUE TITLE
Move clear spif in I2C code

### ISSUE THREAD

**Issue by CrasherCourse** [teslaworksumn/HeadMaster#56]
Just move the clearing of the sp interrupt flag out of the send byte function.
Or make a wait function.

More issues likely pending.

**Comment by taylortrimble** [comment]
Clear after this stuff:

> The following events will cause the MSSP Interrupt Flag bit, SSPIF, to be set (MSSP interrupt, if enabled):
> • StartCondition
> • StopCondition
> • DataTransferByteTransmitted/Received • AcknowledgeTransmit
> • RepeatedStart

**Comment by CrasherCourse** [comment]
Pull Request merged.
Issue now obsolete.
