### ISSUE TITLE
Load and Restore FSRs used in ASM

### ISSUE THREAD

**Issue by taylortrimble** [teslaworksumn/HeadMaster#9]
We are using FSRs in the inlline assembly code, but our assembly was designed for when we had total control over the FSRs. Now that we are in C, our FSRs are all shared and shit. We need to test that it's okay for us to use FSR2 without loading and restoring.

**Comment by taylortrimble** [comment]
Both XC8 and C18 _forbid_ the use of FSR0, FSR1, and FSR2 in inline assembly. Which, of course, is all the FSRs. :smile: Kevan is working on translating our DMX ASM code to C, so this issue is moot.

**Comment by kevana** [comment]
0_o That's unfortunate. Back to the grindstone....

**Comment by taylortrimble** [comment]
I know, right? It's almost like C eats up resources or something. :stuck_out_tongue_closed_eyes:
